### ISSUE TITLE
[USER STORY] Set Up Heroku for Lego Collections App

### ISSUE THREAD

**Issue by crazycooky77** [crazycooky77/ci_project4#11]
As a **developer**, I can **deploy my app to Heroku** so that **external users can access and interact with the app**.

### Acceptance Criteria
- App created on Heroku
- GitHub repository linked to Heroku app
- ElephantSQL instance linked to Heroku app
- Necessary environment variables (Config Vars) created

### Tasks
- [x] Create a new app on [Heroku](https://dashboard.heroku.com/apps)
  - New > Create new app
  - Select an app name (lego-collection) and region
  - Create app
- [x] Connect GitHub to Heroku
  - On the Deploy page for the app, locate the Deployment method section
  - Click GitHub/Connect to GitHub
  - If necessary, log in, and then select the appropriate repository
  - Search and Connect
- [x] Enable Automatic Deploys on the Deploy page for the app on Heroku
- [x] Set the necessary Config Vars in Settings for the Heroku app
  - Review Config Vars
  - Key "DISABLE_COLLECTSTATIC" with value "1" and Add
  - In the previously created ElephantSQL instance, copy the URL from the instance details
  - Add the key "DATABASE_URL" to Heroku with the value equal to your copied ElephantSQL URL
  - Add the key "HEROKU_HOSTNAME" with the value equal to the URL of your Heroku app, excluding https:// and the last /
    - Click Open app in the upper right to get this URL if needed
  - Add the key "SECRET_KEY" with the value of an auto-generated Django secret key
    - Use [this link](https://djecrety.ir/) or just Google "Django secret key generator"

### Linked EPIC
- #5
