### ISSUE TITLE
[USER STORY] Account Creation

### ISSUE THREAD

**Issue by crazycooky77** [crazycooky77/ci_project4#12]
As a **user**, I can **create an account in the app** so that **I can save and retrieve my lego collections through my account**.

### Acceptance Criteria
- Create account with the following options
  - Username
  - Password
  - Email address

### Tasks
- [x] Account creation feature
  - Add options for username, password, and email address
- [x] Encrypt passwords
- [x] Check for an existing account with that username or email
  - If account exists, offer username reminder and password reset
- [x] Check that minimum password requirements are met

### Linked EPIC
- #1
