### ISSUE TITLE
[USER STORY] Account deletion

### ISSUE THREAD

**Issue by crazycooky77** [crazycooky77/ci_project4#14]
As a **user**, I can **delete my account** so that **my data is no longer stored when I don't want to use the app anymore**.

### Acceptance Criteria
- Delete account option

### Tasks
- [x] Delete account
- [x] Warning that collections will be deleted and action cannot be undone
- [x] Delete all user account data from the database upon confirmation
- [x] Delete all collection data for that user account from the database

### Linked EPIC
- #1
