### ISSUE TITLE
[USER STORY] Password Reset

### ISSUE THREAD

**Issue by crazycooky77** [crazycooky77/ci_project4#15]
As a **user**, I can **reset my password** so that **I can regain access to my account if I forget it**.

### Acceptance Criteria
- Password reset option

### Tasks
- [x] Reset password button
- [x] Email to the user with a link to set a new password
- [x] Ensure minimum password requirements are met
- [x] Encrypt passwords

### Linked EPIC
- #1
