### ISSUE TITLE
[USER STORY] User Profile Page

### ISSUE THREAD

**Issue by crazycooky77** [crazycooky77/ci_project4#17]
As a **user**, I can **view my own and my friend's user profiles** so that **I can see the number of collections at a glance, and links to collections and favourites**.

### Acceptance Criteria
- User profile page
- Public, semi-private, and private visibility
- Numbers of and links to collections and favourites

### Tasks
- [x] Profile page creation
- [x] Number of sets in collections
- [x] Private visibility by default
- [ ] Semi-private visibility allows friends/shared users to view profile page
- [ ] Public visibility lets anyone see the profile page

### Linked EPIC
- #1

**Comment by crazycooky77** [comment]
Visibility/sharing features will be implemented at a later stage. Moving back to To Do list (Could Have, as all Should Have features (profile page, # of sets, privacy visibility and default) have been implemented)
