### ISSUE TITLE
[USER STORY] Update Lego Collection

### ISSUE THREAD

**Issue by crazycooky77** [crazycooky77/ci_project4#22]
As a **user**, I can **edit my collection and the sets therein** so that **make updates to ensure I always have the latest information saved**.

### Acceptance Criteria
- Edit sets in collections
- Add sets to collections
- Delete sets from collections

### Tasks
- [x] Edit sets in collection
- [x] Add sets to collections
- [x] Delete sets from collections
- See #20 for all editing and adding

### Linked EPIC
- #2
