### ISSUE TITLE
[USER STORY] Custom Links

### ISSUE THREAD

**Issue by crazycooky77** [crazycooky77/ci_project4#26]
As a **developer**, I can **create custom links for different filter settings for collections** so that **users can access their collection in any specific, filtered, view**.

### Acceptance Criteria
- Custom links for collections

### Tasks
- [ ] Plain link for collection
- [ ] Custom links according to filtered status
- [ ] Custom links according to sorted status

### Linked EPIC
- #7 
- #3
