### ISSUE TITLE
[USER STORY] Automated Testing

### ISSUE THREAD

**Issue by crazycooky77** [crazycooky77/ci_project4#49]
As a **developer**, I can **build and run automated tests** so that **I can ensure the website's functionality is working as expected, without having to test everything manually**.

### Acceptance Criteria
- <strike>List all classes/functions in forms.py and views.py</strike>
- <strike>Create a test file for each (forms and views)</strike>
- <strike>Write tests for each</strike>
- <strike>Run python coverage to check where there are holes in automated testing</strike>

### Tasks
- [x] List all classes/functions in forms.py and views.py
- [x] Create a test file for each (forms and views)
- [x] Write tests for each
- [x] Run python coverage to check where there are holes in automated testing

### Linked EPIC
- https://github.com/crazycooky77/ci_project4/issues/4

**Comment by crazycooky77** [comment]
Completed and documented: https://github.com/crazycooky77/ci_project4?tab=readme-ov-file#automated-testing
