### ISSUE TITLE
[USER STORY] Set Up GitHub for Lego Collections App

### ISSUE THREAD

**Issue by crazycooky77** [crazycooky77/ci_project4#8]
As a **developer**, I can **have all my issues and code stored in GitHub** so that **I can track progress and have proper version control**.

### Acceptance Criteria
- GitHub repository created with CI template
- Issue templates created
- Issues created and organised
- Repository set up in GitHub Desktop

### Tasks
- [x] Clone [Code Institute](https://github.com/Code-Institute-Org/ci-full-template) template
  - Use this template
  - Create a [new repository](https://github.com/crazycooky77/ci_project4)
- [x] Create [new project board](https://github.com/users/crazycooky77/projects/1)
  - Projects > Link a project > New project
- [x] Create Issues templates
  - Settings > General > Features > Set up templates
  - Add template > Custom template
  - Preview and edit > Propose changes
  - Commit changes to main branch
- [x] Create Labels
  - Issues > Labels > New label
- [x] Create EPICs user stories to plan out necessary features/work for the app
  - Issues > New issue
- [x] Link all [Issues](https://github.com/crazycooky77/ci_project4/issues) to the [project board](https://github.com/users/crazycooky77/projects/1)
- [x] Code > Open with GitHub Desktop > Clone

### Linked EPIC
- #5
