### ISSUE TITLE
[USER STORY] Set up PyCharm for Lego Collections App

### ISSUE THREAD

**Issue by crazycooky77** [crazycooky77/ci_project4#9]
As a **developer**, I can **set up PyCharm** so that **I can create, edit, and test my app locally**.

### Acceptance Criteria
- PyCharm project created
- PyCharm project linked to GitHub
- Django installed and app created
- Necessary environment variables set

### Tasks
- [x] File > Open > select local GitHub directory
- [x] In PyCharm's Terminal, install and extract the necessary libraries
  - `pip3 install django==4.2.1`
  - `pip3 install gunicorn`
  - `pip3 freeze local > requirements.txt`
- [x] In PyCharm's Terminal, create the Django project and app
  - `django-admin startproject ci_project4 .`
  - `python3 manage.py startapp lego_collection`
- [x] Update the settings.py file with the following (according to the Hello Django > Deployment chapter of Code Institute's Full Stack Frameworks (FST) (Deprecated) module)
  - Add `import os` to the file imports
  - Add `import dj_database_url` to the file imports
  - Under the file imports, add `development = os.environ.get('DEVELOPMENT', False)`
  - Change the SECRET_KEY line to `SECRET_KEY = os.environ.get('SECRET_KEY', '')`
  - Change `DEBUG = True` to `DEBUG = development`
  - Add the app name into the INSTALLED_APPS section
  - In the ALLOWED_HOSTS section, write an if statement to check the development status
    - `if development:`
       `    ALLOWED_HOSTS = ['127.0.0.1']`
       `else:`
       `    ALLOWED_HOSTS = [os.environ.get('HEROKU_HOSTNAME')]`
- [x] Update the other necessary project and app files
  - Import HttpResponse from django.http in views.py
    - `from django.http import HttpResponse`
  - Create a basic Hello World function in views.py to test the setup
    - `def hello_world(request):`
       `    return HttpResponse('Hello, World!')`
  - Import views.py in urls.py
    - `from lego_collection.views import hello_world`
  - Add the new path into urlpatterns in urls.py
    - `path('', hello_world, name='hello world')`
- [x] Create a Procfile file in the main folder for the app
  - Right-click on the main folder (ci_project4)
  - New > File > Procfile > Enter key
  - Add `web: gunicorn codestar.wsgi` to the file and save
- [x] Run the server to ensure the initial app is set up correctly
  - `python3 manage.py runserver`
- [x] Environment variables set in PyCharm > Settings > Tools > Terminal
  - Open the Environment variables window with the small paper icon on the right
  - Add the name "DEVELOPMENT" with the value "True"
  - Add the name "HEROKU_HOSTNAME" with the value of your Heroku app URL excluding the first https:// and the last /
    - Go to your Heroku app and click Open app in the upper right to get the URL
  - Add the name "SECRET_KEY" with the value of your auto-generated Django secret key added to Heroku
- [x] Commit the changes to GitHub

### Linked EPIC
- #5
